Akvile/work on courses
vu-code-cartel/studyzen pull request #15
Opened 2023-09-19 11:29 UTC by AkvileR

- Finished implementing CRUD functionality to courses
- Made course description an optional field to fulfill a requirement.

2023-09-19 14:00 UTC, arminasbrazenas requested changes

2023-09-19 14:00 UTC, arminasbrazenas commented on studyzen/Courses/Requests/CreateCourseRequest.cs
> +    public string? Description { get; }
lets leave it as non-nullable and make constructor accept string with default set as empty string

2023-09-19 14:00 UTC, arminasbrazenas commented on studyzen/Courses/CourseService.cs
> +    public bool DeleteCourse(int id)
No need to call GetCourseById, it is done by UnitOfWork Delete method already.

Also, if a course is already deleted, then we the request is completed successfully, since we've done what was asked for. So we can just return void.

2023-09-19 14:00 UTC, arminasbrazenas commented on studyzen/Courses/CourseService.cs
> +        var oldCourse = _unitOfWork.Courses.GetById(id);
Surround ifs in brackets, as it is done in LectureService

2023-09-19 14:00 UTC, arminasbrazenas commented on studyzen/Courses/CourseService.cs
> +        var newCourse = new Course(request.Name,request.Description);
Space between constructor properties

2023-09-19 14:00 UTC, arminasbrazenas commented on studyzen/Courses/CoursesController.cs
> +        return result == false ? NotFound() : Ok();
Return NoContent

2023-09-19 14:00 UTC, arminasbrazenas commented on studyzen/Courses/Course.cs
> +    public Course(string name, string description = "") : base(default)
lets keep empty string in Create request

2023-09-19 16:41 UTC, arminasbrazenas approved these changes

2023-09-20 19:14 UTC, vestacic approved these changes
Good job

2023-09-20 19:19 UTC, merged