Evelina , readme file
vu-code-cartel/studyzen pull request #3
Opened 2023-09-10 11:10 UTC by EvelinaTemnolonskyte

Nice team , nice work

2023-09-10 11:38 UTC, arminasbrazenas commented
Lets use README.md for our documentation, here is an example for VS Code: https://code.visualstudio.com/docs/languages/markdown

2023-09-10 11:42 UTC, arminasbrazenas commented
Pull request name should be descriptive. 1st and 2nd tips from [this](https://blog.montrealanalytics.com/4-tips-for-effective-pull-request-naming-f60793998f04) tutorial seem to elaborate it.

2023-09-10 11:43 UTC, arminasbrazenas commented
Also, for future reference, name the branch according to the feature that you are implementing or even have it under your own directory: e.g. evelina/update-readme

2023-09-10 16:28 UTC, EvelinaTemnolonskyte commented
Thank you!

2023-09-11 17:17 UTC, vestacic requested changes

2023-09-11 17:17 UTC, vestacic commented on studyzen
I believe no modules should be added yet

2023-09-11 18:33 UTC, EvelinaTemnolonskyte commented
Have solved this in new pull request

2023-09-11 18:44 UTC, arminasbrazenas commented
> Have solved this in new pull request

Nice, next time there is no need to create a new pull request. You can do the following:

1. `git log`
2. find id of the commit that you want to revert your changes to
3. `git reset {commitId}` (be aware that there is soft and hard reset)
4. make changes
5. `git push` (might need to use `--force` flag)

2023-09-11 18:44 UTC, closed without merging