Vesta/add authentication frontend
vu-code-cartel/studyzen pull request #63
Opened 2023-11-26 20:41 UTC by vestacic

As promised, finally users became visible. As I don't have much experience with front-end development, please, don't be too judgemental and mean.

2023-11-27 19:29 UTC, arminasbrazenas requested changes

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/hooks/useAppStore.ts
> +  isLoggedIn: false,
I suggest having a type User, containing id, username and role. Then have the state User | null, then no need for isLoggedIn and one state in the whole place, which changes together

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignInModal.tsx
> +                    <TextInput
https://mantine.dev/core/password-input/

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +                        placeholder={t('Authentication.Field.Password.Label')}
https://mantine.dev/core/password-input/

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +        <Modal opened={isOpen} onClose={handleClose} title={t('Authentication.Title.SignUp')}>
suggestion for pages to copy from if u change to pages: https://ui.mantine.dev/category/authentication/

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +    const form = useForm({
```suggestion
    const form = useForm<RegisterRequest>({
```

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignInModal.tsx
> +    const form = useForm({
```suggestion
    const form = useForm<LoginRequest>({
```

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignInModal.tsx
> +                <Text
https://mantine.dev/core/anchor/ with Link, e.g.

```ts
<Anchor component={Link} to={AppRoutes.SignUp}>
  Create account
</Anchor>
```

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/hooks/api/useAccountsApi.ts
> +    const fetchUserInfo = async () => {
seems like a redundant function since you can call react hook only at top level

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/hooks/api/useAccountsApi.ts
> +            await axiosClient.post(`${ACCOUNTS_API_URL}/login`, request, { withCredentials: true });
I think withCredentials is already set in axiosClient

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +            role: 'student',
I think the Role enum can be used

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +                            { value: 'student', label: t('Authentication.Role.Student') },
I think the Role enum can be used for value

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +                        placeholder={t('Authentication.Field.FirstName.Label')}
It should be labels, not placeholders, since you will no longer see, what fields you filled up... e.g. you might accidentally swap first name with last name or username

2023-11-27 19:29 UTC, arminasbrazenas commented on client/src/components/AppInitializer.tsx
> +        fetchUserInfo();
you can use react-query and query user info without useEffect, since hooks only work at top level.. querying in useEffect is an anti-pattern

2023-11-27 19:33 UTC, arminasbrazenas commented on client/src/components/account/SignUpModal.tsx
> +            password: (value) => (value ? null : t('Authentication.Field.Password.Error.Required')),
also, EF Core has password rules set, so if I send `testas` I get 200, but no account is created.. can fix it quick in frontend or backend, but then errors won't be that clean probably for now

2023-11-27 23:15 UTC, vestacic commented on client/src/hooks/api/useAccountsApi.ts
> +    const fetchUserInfo = async () => {
It is actually used here `useLogin` to get user data after login as the login function in back-end only sets cookies.

2023-11-28 00:11 UTC, vestacic commented on client/src/components/account/SignUpModal.tsx
> +            password: (value) => (value ? null : t('Authentication.Field.Password.Error.Required')),
yes, good point, maybe this handling could be left as another task

2023-11-28 06:33 UTC, arminasbrazenas approved these changes

2023-11-28 06:34 UTC, arminasbrazenas commented
Good job

2023-11-28 08:10 UTC, AkvileR approved these changes

2023-11-28 09:46 UTC, merged